In [1]:
import numpy as np
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [4]:
# 1.) How many negative numbers are there?

negative = a < 0
negative

print("This is how many negative numbers there are: ",len(a[negative]))

This is how many negative numbers there are:  4


In [5]:
# 2.) How many positive numbers are there?

positive = a > 0
positive

print("This is how many negative numbers there are: ",len(a[positive]))

This is how many negative numbers there are:  5


In [6]:
# 3.) How many even positive numbers are there?

#positive = a % 2 == 0
#positive = a > 0 
positive_even = a[(a>0) & (a%2 == 0)]
positive_even

print("This is how many positive even numbers there are: ", len(positive_even))

This is how many positive even numbers there are:  3


In [7]:
# 4.) If you were to add 3 to each data point, how many positive numbers would there be?

a2 = a + 3
a2

positive2 = a2 > 0
positive2
print("This is how many positive numbers there are when you add 3 to the array: ", len(a[positive2]))

This is how many positive numbers there are when you add 3 to the array:  10


In [8]:
# 5.) If you squared each number, what would the new mean and standard deviation be?

a3 = a**2
a3


print("This is the new standard deviationg: ",np.std(a))
print("This is the new mean: ",np.mean(a))


print("\n\nThis is the new standard deviationg: ",np.std(a3))
print("This is the new mean: ",np.mean(a3))

This is the new standard deviationg:  8.06225774829855
This is the new mean:  3.0


This is the new standard deviationg:  144.0243035046516
This is the new mean:  74.0


In [9]:
# 6.) A common statistical operation on a dataset is centering.
# This means to adjust the data such that the mean of the data is 0. 
#This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

a_is_mean = np.mean(a)

centering = a - a_is_mean
centering

center = np.mean(centering)

print(center)

0.0


In [10]:
# 7.) Calculate the z-score for each data point. Recall that the z-score is given by:
# Z = x − μ σ

z =  a - np.mean(a)

z_score = z / np.std(a)

print(z_score)

[ 0.12403473  0.86824314  1.11631261  2.48069469 -0.62017367 -0.49613894
 -0.3721042  -0.3721042  -0.3721042  -1.11631261  0.         -1.24034735]


# 8.) Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and
# add your solutions.

In [11]:
c = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [12]:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
sum_of_a = np.sum(c)
print(sum_of_a)

55


In [13]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
min_of_c = np.min(c)

print(min_of_c)

1


In [14]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

max_of_c = np.max(c)

print(max_of_c)

10


In [15]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

mean_of_c = np.mean(c)

print(mean_of_c)

5.5


In [16]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

product_of_c = np.product(c)

print(product_of_c)

3628800


In [17]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

squares_of_c = np.square(c)

print(squares_of_c)

[  1   4   9  16  25  36  49  64  81 100]


In [21]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
c  = np.array(c)
odds_in_c = (c%2 != 0)

print(c[odds_in_c])

[1 3 5 7 9]


In [22]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.
evens_in_c = (c%2 == 0)

print(c[evens_in_c])

[ 2  4  6  8 10]


# Set up 2

In [28]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [39]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
#sum_of_b = 0
#for row in b:
#    sum_of_b += sum(row)
    
b = np.array(b)

sum_of_b = np.sum(b)
print(sum_of_b)

33


In [37]:
# Exercise 2 - refactor the following to use numpy. 
#min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])

min_of_b = np.min(b)

print(min_of_b)

3


In [36]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
#max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

max_of_b = np.max(b)

print(max_of_b)

8


In [41]:
# Exercise 4 - refactor the following using numpy to find the mean of b
#mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

mean_of_b - np.mean(b)

print(mean_of_b)

5.5


In [43]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
#product_of_b = 1
#for row in b:
#    for number in row:
#        product_of_b *= number
     
product_of_b = np.product(b)    
print(product_of_b)

20160


In [46]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
#squares_of_b = []
#for row in b:
#    for number in row:
#        squares_of_b.append(number**2)
        
squares_of_b = np.square(b)

print(squares_of_b)

[[ 9 16 25]
 [36 49 64]]


In [50]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
#odds_in_b = []
#for row in b:
#    for number in row:
#        if(number % 2 != 0):
#            odds_in_b.append(number)
            
odds_in_b = b % 2 != 0
print(b[odds_in_b])

[3 5 7]


In [51]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
#evens_in_b = []
#for row in b:
#    for number in row:
#        if(number % 2 == 0):
#            evens_in_b.append(number)
            
evens_in_b = b % 2 == 0
print(b[evens_in_b])

[4 6 8]


In [53]:
# Exercise 9 - print out the shape of the array b.

print(np.shape(b))

(2, 3)


In [55]:
# Exercise 10 - transpose the array b.

print(np.transpose(b))

[[3 6]
 [4 7]
 [5 8]]


In [56]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

print(np.reshape(b, (1,6)))

[[3 4 5 6 7 8]]


In [57]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

print(np.reshape(b, (6,1)))

[[3]
 [4]
 [5]
 [6]
 [7]
 [8]]


# Setup 3

In [60]:
d = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

d = np.array(d)

In [61]:
# HINT, you'll first need to make sure that the "d" variable is a numpy array prior to using numpy array methods.
# Exercise 1 - Find the min, max, sum, and product of d.

min_d = np.min(d)
max_d = np.max(d)
sum_d = np.sum(d)
product_d = np.product(d)

print("Min: {}\nMax: {}\nSum: {}\nProduct: {}".format(min_d, max_d, sum_d, product_d))


Min: 1
Max: 9
Sum: 45
Product: 362880


In [62]:
# Exercise 2 - Determine the standard deviation of d.
std_d = np.std(d)

print("Standard deviation: ", std_d)

Standard deviation:  2.581988897471611


In [63]:
# Exercise 3 - Determine the variance of d.

var_d = np.var(d)

print(var_d)

6.666666666666667


In [65]:
# Exercise 4 - Print out the shape of the array d
print(np.shape(d))

(3, 3)


In [66]:
# Exercise 5 - Transpose d and print out transposed result.
trans_b = np.transpose(d)

print(trans_b)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [68]:
# Exercise 6 - Get the dot product of the array d with d. 

dot_d = np.dot(d,d)
print(dot_d)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [69]:
# Exercise 7 - Write the code necessary to sum up the result of d times d transposed. Answer should be 261

d_times_trans = d * trans_b

print(np.sum(d_times_trans))

261


In [70]:
# Exercise 8 - Write the code necessary to determine the product of d times d transposed. 
# Answer should be 131681894400.


print(np.product(d_times_trans))


131681894400


## Setup 4

In [80]:
e = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

e = np.array(e)

In [76]:
# Exercise 1 - Find the sine of all the numbers in d

print(np.sin(e))

[[ 0.89399666 -0.98803162  0.85090352  0.          0.58061118 -0.80115264]
 [ 0.85090352 -0.89399666  0.98803162 -0.17604595  0.89399666  0.        ]
 [-0.30481062  0.85090352 -0.85090352  0.89399666 -0.85090352 -0.80115264]]


In [77]:
# Exercise 2 - Find the cosine of all the numbers in d

print(np.cos(e))

[[-0.44807362  0.15425145  0.52532199  1.          0.81418097 -0.59846007]
 [ 0.52532199 -0.44807362  0.15425145  0.98438195 -0.44807362  1.        ]
 [-0.95241298  0.52532199  0.52532199 -0.44807362  0.52532199 -0.59846007]]


In [78]:
# Exercise 3 - Find the tangent of all the numbers in d

print(np.tan(e))

[[-1.99520041 -6.4053312   1.61977519  0.          0.71312301  1.33869021]
 [ 1.61977519  1.99520041  6.4053312  -0.17883906 -1.99520041  0.        ]
 [ 0.32004039  1.61977519 -1.61977519 -1.99520041 -1.61977519  1.33869021]]


In [81]:
# Exercise 4 - Find all the negative numbers in d

neg_e = e < 0
print(e[neg_e])

[-90 -30 -45 -45]


In [82]:
# Exercise 5 - Find all the positive numbers in d

positive_e = e > 0
print(e[positive_e])

[ 90  30  45 120 180  45 270  90  60  45  90 180]


In [84]:
# Exercise 6 - Return an array of only the unique numbers in d.

print(np.unique(e))

[-90 -45 -30   0  30  45  60  90 120 180 270]


In [85]:
# Exercise 7 - Determine how many unique numbers there are in d.
print(len(np.unique(e)))

11


In [86]:
# Exercise 8 - Print out the shape of d.
print(np.shape(e))

(3, 6)


In [87]:
# Exercise 9 - Transpose and then print out the shape of d.

print(np.transpose(e))

[[ 90  45  60]
 [ 30 -90  45]
 [ 45 -30 -45]
 [  0 270  90]
 [120  90 -45]
 [180   0 180]]


In [88]:
# Exercise 10 - Reshape d into an array of 9 x 2

print(np.reshape(e,(9,2)))


[[ 90  30]
 [ 45   0]
 [120 180]
 [ 45 -90]
 [-30 270]
 [ 90   0]
 [ 60  45]
 [-45  90]
 [-45 180]]
